[project]
name = "forlife_insurance"
version = "0.1.0"
description = "Projeto de dados para uma seguradora de vida, carros e automéveis"
authors = [
    {name = "Rodrigo Silva dataforge.br@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "sqlalchemy>=2.0.49,<3.0.0",
    "faker>=37.11.0,<38.0.0",
    "fastapi>=0.115.12,<1.0.0",
    "psycopg2-binary>=2.9.12,<3.0.0",
    "python-dotenv>=1.0.0,<2.0.0",
    "pydantic[email] (>=2.13.3,<3.0.0)",
    "pydantic-extra-types[phonenumbers] (>=2.11.1,<3.0.0)",
    "pydantic-br (>=1.1.0,<2.0.0)",
    "uvicorn>=0.34.0,<1.0.0",
]

[dependency-groups]
dev = [
    "black>=26.3.1,<27.0.0",
    "isort>=8.0.1,<9.0.0",
    "bandit>=1.9.4,<2.0.0",
    "pre-commit>=4.5.1,<5.0.0",
    "pytest>=8.0.0,<9.0.0"
]

[project.scripts]
forlife-seed = "forlife_insurance.seed.runner:main"
forlife-extract-apolices = "forlife_insurance.extract.jobs.apolice:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
