[tool.poetry]
name = "forlife-insurance-api"
version = "0.1.0"
description = "API transacional independente do domínio Forlife"
authors = ["Rodrigo Silva <dataforge.br@gmail.com>"]
readme = "README.md"
packages = [{ include = "forlife_insurance_api", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = ">=0.115.12,<1.0.0"
uvicorn = ">=0.34.0,<1.0.0"
pydantic = ">=2.13.3,<3.0.0"
pydantic-extra-types = { version = ">=2.11.1,<3.0.0", extras = ["phonenumbers"] }
pydantic-br = ">=1.1.0,<2.0.0"
forlife-insurance-core = { path = "../forlife-insurance-core", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
